#! /bin/sh
# $Id: gdbpatchno,v 1.1 2006/12/29 20:35:43 jkratoch Exp $
# Print the first unused patch number across all the current package's branches.

echo $[1+$(cat ../*/*.spec|sed -n 's/^[# %]*patch\([0-9]*\).*$/\1/p'|sort -rnu|head -n1)]
